version: '3'
services:
  wordtopdf:
    build: .
    container_name: wordtopdf-converter
    ports:
      - "5000:5000"
    environment:
      - DOCKER=yes
    volumes:
      - ./code:/usr/src/app
      - temp_data:/usr/src/app/temp
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/hello"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

volumes:
  temp_data: